name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libltdl-dev libffi-dev libssl-dev python3-dev zlib1g-dev openjdk-17-jdk unzip zip autoconf libtool pkg-config
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kpbtr-apk
        path: bin/*.apk
